<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	  <StartupObject>NewAPP.App</StartupObject>
	  <AssemblyName>Neurowarehouse</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EPPlus" Version="8.5.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.7" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.7" />
    <PackageReference Include="Velopack" Version="0.0.1298" />
  </ItemGroup>

</Project>
